title: Tibia - Mietar

autoheal:
  enabled: true
  spells:
    - key: F3
      minMana: 3
      minHealth: 88
  potions:
    - key: F4
      minMana: 70
    - key: F5
      minHealth: 50
      priority: -1

combo:
  enabled: true
  attacks:
    - key: F7
      minMana: 15
      cooldown: 2
      type: SPELL
    - key: F8
      cooldown: 2
      type: RUNE
  switch:
    enabled: true
    key: CAPS_LOCK

foodeater:
  enabled: true
  key: F9

exchange:
  enabled: true

autotarget:
  enabled: true

magictraining:
  enabled: true
  burners:
    - key: F3
      minMana: 90
    - key: F10
      minMana: 90

refiller:
  enabled: true
  from:
    container: BACKPACK
    type: CRYSTAL
  to:
    container: QUIVER
    type: BLUE
  delay: 10
