title: Tibia - Mietar

autoheal:
  enabled: true
  spells:
    - key: F3
      min_mana: 3
      min_health: 88
  potions:
    - key: F4
      min_mana: 70
    - key: F5
      min_health: 50
      priority: -1

combo:
  enabled: true
  attacks:
    - key: F7
      min_mana: 15
      delay: 2
      type: SPELL
    - key: F8
      delay: 2
      type: RUNE
  switch:
    key: CAPS_LOCK

foodeater:
  enabled: true
  key: F9

exchange:
  enabled: true

autotarget:
  enabled: true

autoloot:
  enabled: true
  mouse_button: RIGHT
  delay: 10

magictraining:
  enabled: true
  burners:
    - key: F3
      min_mana: 90
    - key: F10
      min_mana: 90

refiller:
  enabled: true
  from:
    container: CRYSTAL
    type: BACKPACK
  to:
    container: BLUE
    type: QUIVER
  delay: 10
