title: Tibia - Zaraki Kenpachi

autoheal:
  enabled: true
  spells:
    - key: F1
      min_mana: 3
      min_health: 94
  potions:
    - key: F4
      min_mana: 30
    - key: F5
      min_health: 84

combo:
  enabled: true
  attacks:
    - key: N3
      min_mana: 15
      delay: 0.1
      type: SPELL
    - key: F7
      min_mana: 10
      delay: 2
      type: SPELL
    - key: N2
      min_mana: 11
      delay: 0.1
      type: SPELL
    - key: F8
      min_mana: 10
      delay: 2
      type: SPELL
#      min_monsters_count: 2
#    - key: N1
#      min_mana: 10
#      delay: 2
#      type: SPELL
#      max_monsters_count: 1
  switch:
    key: CAPS_LOCK
  randomization:
    enabled: true
    hp_gate: 60
    max: 0.2 # sec
    min: 0 # sec

foodeater:
  enabled: true
  key: F9

exchange:
  enabled: true

autotarget:
  enabled: false

autoloot:
  type: ON_KEY
  key: SPACE
  mouse_button: RIGHT
  loot_cooldown: 0
  enabled: true

autocast:
  enabled: true
  key: F2
  delay: 600

magictraining:
  enabled: true
  burners:
    - key: F1
      min_mana: 90
      delay: 1.05

refiller:
  enabled: false
